OPENAI_API_KEY = "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"
OPENAI_PROJECT_ID = "org-EWc9hLqeJww43GAHkQjg56w4"

